### ISSUE TITLE
Add one (or more) license(s)

### ISSUE THREAD

**Issue by zbeekman** [samharrison7/fortran-error-handler#6]
Hi, very cool library! I'm considering using it in some projects, or extending it, but that's hard to do without a license.

I know choosing a license can be confusing. My personal recommendation is the MIT license due to its permissiveness and compatibility with other open source licenses and in corporate/closed source settings. https://choosealicense.com/ is a great resource to help you get started.

Or, if you can't decide, as the copyright holder you can even give people the option to use your library under their choice of licenses from a set you define. For an example of this, see https://github.com/szaghi/FACE

**Comment by samharrison7** [comment]
Sorry for the slow response! I've now added an MIT license. Feel free to use and abuse as you desire :)
